database:
  dialect: mysql
  user: root
  password:
  host:
  port:
  dbname: zk-doge
  max_idle_conn: 10
  max_open_conn: 100
  debug: true
  auto_migrate: false

rpc:
  mainnet_polygon: wss://polygon-mainnet.g.alchemy.com/v2/project_id
  mainnet_eth: wss://mainnet.infura.io/ws/v3/project_id
  testnet_goerli: wss://goerli.infura.io/ws/v3/project_id
  testnet_wallaby: wss://wss.wallaby.node.glif.io/apigw/lotus/rpc/v0
  testnet_mumbai: wss://matic-mumbai.chainstacklabs.com

gin:
  mode: debug
  listen: ":9999"

redis:
  network: tcp
  address:
  port: 6379
  db: 11
  password:

session:
  expires_time: 604800
  key_pairs: be10c141-2ca1-414f-9216-ece26af215f9

email:
  auth_code:
  from:
  username: 