database:
  dialect: mysql
  user: root
  password:
  host:
  port:
  dbname: zk-doge
  max_idle_conn: 10
  max_open_conn: 100
  debug: true
  auto_migrate: false

gin:
  mode: debug
  listen: ":9999"

redis:
  network: tcp
  address:
  port: 6379
  db: 11
  password:

session:
  expires_time: 604800
  key_pairs: be10c141-2ca1-414f-9216-ece26af215f9

email:
  auth_code:
  from:
  username: 